string function_block_name
bool bool_param1
bool bool_param2
bool bool_param3
float32 float_param1
float32 float_param2
float32 float_param3
int16 int_param1
int16 int_param2
int16 int_param3
---
bool success
int16 state
string msg
---
int8 msg_type
string msg


