/ads_node:
  ros__parameters:
    robot_name: "Giskard"

    remote_ip: '10.10.10.5'
    remote_ads: '5.152.54.58.1.1'

    CLIENT_NETID: '10.10.10.50.1.1'
    CLIENT_IP: '10.10.10.50'

    PLC_IP: '10.10.10.5'
    PLC_NET_ID: '5.152.54.58.1.1'
    

